insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00331', 'Retraining', '2026-04-24', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00482', 'Retraining', '2025-09-09', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00425', 'Retraining', '2025-09-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00195', 'Safety Coaching', '2025-09-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00020', 'Safety Coaching', '2025-07-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00065', 'Retraining', '2026-02-21', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00374', 'Retraining', '2026-05-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00328', 'Retraining', '2025-10-06', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00280', 'Safety Coaching', '2025-07-09', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00458', 'Licence Review', '2026-03-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00047', 'Licence Review', '2026-01-16', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00481', 'Retraining', '2026-01-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00441', 'Licence Review', '2025-11-30', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00385', 'Retraining', '2025-09-30', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00330', 'Retraining', '2026-01-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00387', 'Safety Coaching', '2026-06-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00363', 'Licence Review', '2025-09-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00301', 'Retraining', '2026-02-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00322', 'Retraining', '2026-02-04', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00082', 'Licence Review', '2026-03-22', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00464', 'Safety Coaching', '2026-01-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00367', 'Retraining', '2025-12-26', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00063', 'Licence Review', '2026-06-08', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00046', 'Licence Review', '2025-09-25', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00457', 'Licence Review', '2025-12-29', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00407', 'Retraining', '2025-08-19', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00384', 'Licence Review', '2025-07-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00283', 'Licence Review', '2026-02-10', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00189', 'Retraining', '2026-04-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00278', 'Retraining', '2025-12-18', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00408', 'Licence Review', '2026-06-30', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00191', 'Retraining', '2025-10-10', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00371', 'Retraining', '2026-06-12', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00462', 'Licence Review', '2025-09-24', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00059', 'Safety Coaching', '2026-05-14', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00459', 'Licence Review', '2026-03-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00291', 'Safety Coaching', '2025-12-21', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00143', 'Retraining', '2025-12-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00112', 'Retraining', '2026-05-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00018', 'Licence Review', '2026-03-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00255', 'Retraining', '2025-12-22', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00202', 'Licence Review', '2025-10-31', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00031', 'Retraining', '2025-07-25', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00222', 'Retraining', '2025-09-27', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00127', 'Retraining', '2026-03-24', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00029', 'Retraining', '2025-07-03', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00331', 'Safety Coaching', '2025-11-17', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00140', 'Retraining', '2026-06-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00220', 'Licence Review', '2026-03-10', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00218', 'Safety Coaching', '2026-01-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00029', 'Licence Review', '2025-08-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00381', 'Retraining', '2026-05-29', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00208', 'Retraining', '2026-01-31', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00435', 'Licence Review', '2026-05-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00029', 'Retraining', '2025-10-30', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00003', 'Licence Review', '2025-10-07', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00381', 'Retraining', '2026-04-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00022', 'Retraining', '2026-03-27', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00007', 'Retraining', '2026-02-21', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00252', 'Safety Coaching', '2025-07-10', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00246', 'Safety Coaching', '2025-10-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00419', 'Safety Coaching', '2025-10-16', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00106', 'Safety Coaching', '2026-01-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00212', 'Licence Review', '2025-10-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00268', 'Retraining', '2025-11-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00347', 'Licence Review', '2026-01-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00446', 'Licence Review', '2026-01-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00310', 'Licence Review', '2026-02-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00087', 'Retraining', '2025-07-12', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00335', 'Safety Coaching', '2026-04-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00053', 'Retraining', '2025-12-11', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00222', 'Safety Coaching', '2025-09-22', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00273', 'Safety Coaching', '2026-03-30', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00353', 'Safety Coaching', '2026-06-06', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00378', 'Safety Coaching', '2026-05-26', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00428', 'Licence Review', '2026-06-04', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00220', 'Licence Review', '2026-05-11', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00254', 'Safety Coaching', '2025-08-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00248', 'Licence Review', '2026-02-19', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00477', 'Retraining', '2025-10-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00277', 'Retraining', '2025-10-21', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00295', 'Licence Review', '2026-03-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00330', 'Licence Review', '2026-04-30', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00422', 'Safety Coaching', '2025-09-19', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00390', 'Licence Review', '2025-09-30', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00317', 'Safety Coaching', '2026-02-23', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00167', 'Retraining', '2025-09-20', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00105', 'Safety Coaching', '2025-11-11', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00236', 'Safety Coaching', '2026-01-28', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00094', 'Licence Review', '2026-01-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00258', 'Retraining', '2025-12-24', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00276', 'Retraining', '2025-10-27', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00361', 'Retraining', '2026-02-26', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00072', 'Retraining', '2025-10-20', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00243', 'Safety Coaching', '2025-10-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00130', 'Retraining', '2025-11-24', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00294', 'Retraining', '2025-12-18', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00438', 'Licence Review', '2025-08-22', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00027', 'Licence Review', '2026-05-03', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00042', 'Licence Review', '2026-03-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00065', 'Safety Coaching', '2026-04-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00063', 'Retraining', '2025-09-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00230', 'Licence Review', '2025-08-28', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00431', 'Licence Review', '2025-07-11', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00331', 'Licence Review', '2025-07-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00247', 'Retraining', '2025-12-08', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00443', 'Retraining', '2025-07-13', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00053', 'Safety Coaching', '2026-04-18', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00172', 'Safety Coaching', '2026-05-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00447', 'Safety Coaching', '2025-10-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00406', 'Safety Coaching', '2025-10-05', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00145', 'Retraining', '2026-03-05', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00015', 'Safety Coaching', '2025-12-07', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00163', 'Safety Coaching', '2026-01-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00125', 'Licence Review', '2026-06-17', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00475', 'Safety Coaching', '2025-07-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00014', 'Safety Coaching', '2025-09-28', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00195', 'Retraining', '2026-01-04', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00352', 'Safety Coaching', '2025-09-22', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00078', 'Safety Coaching', '2025-12-31', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00127', 'Licence Review', '2026-01-24', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00290', 'Safety Coaching', '2025-10-31', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00164', 'Licence Review', '2025-10-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00173', 'Licence Review', '2025-10-01', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00016', 'Licence Review', '2025-11-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00275', 'Safety Coaching', '2026-02-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00329', 'Licence Review', '2025-10-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00268', 'Safety Coaching', '2026-02-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00272', 'Safety Coaching', '2025-10-04', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00231', 'Retraining', '2026-06-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00468', 'Licence Review', '2025-08-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00268', 'Licence Review', '2026-06-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00009', 'Safety Coaching', '2025-08-27', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00399', 'Retraining', '2025-12-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00192', 'Retraining', '2026-01-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00051', 'Safety Coaching', '2026-05-09', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00382', 'Safety Coaching', '2025-11-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00026', 'Retraining', '2025-07-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00441', 'Retraining', '2026-05-03', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00022', 'Safety Coaching', '2025-09-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00282', 'Licence Review', '2025-08-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00112', 'Safety Coaching', '2026-03-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00360', 'Safety Coaching', '2026-04-10', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00205', 'Licence Review', '2026-03-11', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00206', 'Licence Review', '2025-10-28', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00100', 'Licence Review', '2025-08-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00015', 'Safety Coaching', '2025-10-26', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00215', 'Retraining', '2026-05-20', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00447', 'Licence Review', '2026-04-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00234', 'Retraining', '2026-06-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00083', 'Licence Review', '2026-06-06', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00300', 'Retraining', '2025-11-17', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00201', 'Safety Coaching', '2025-11-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00479', 'Safety Coaching', '2026-01-04', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00128', 'Licence Review', '2026-01-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00305', 'Licence Review', '2026-02-07', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00217', 'Licence Review', '2025-09-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00356', 'Retraining', '2026-04-10', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00162', 'Safety Coaching', '2025-08-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00185', 'Licence Review', '2025-08-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00224', 'Licence Review', '2025-09-29', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00053', 'Safety Coaching', '2026-03-12', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00296', 'Retraining', '2025-11-16', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00005', 'Retraining', '2025-09-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00159', 'Licence Review', '2026-04-18', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00415', 'Licence Review', '2026-03-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00033', 'Safety Coaching', '2025-09-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00183', 'Safety Coaching', '2025-10-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00466', 'Retraining', '2026-05-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00255', 'Safety Coaching', '2025-12-31', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00116', 'Retraining', '2025-07-08', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00318', 'Retraining', '2026-04-07', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00073', 'Licence Review', '2025-12-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00153', 'Safety Coaching', '2026-03-24', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00461', 'Safety Coaching', '2026-01-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00053', 'Safety Coaching', '2025-10-05', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00114', 'Safety Coaching', '2025-11-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00371', 'Licence Review', '2026-05-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00327', 'Licence Review', '2026-02-10', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00084', 'Safety Coaching', '2025-10-08', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00421', 'Safety Coaching', '2025-09-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00341', 'Retraining', '2025-10-07', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00330', 'Licence Review', '2026-04-18', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00159', 'Retraining', '2026-04-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00213', 'Safety Coaching', '2025-09-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00380', 'Retraining', '2025-12-27', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00028', 'Safety Coaching', '2026-01-30', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00488', 'Safety Coaching', '2025-12-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00279', 'Retraining', '2025-11-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00080', 'Safety Coaching', '2026-01-01', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00255', 'Licence Review', '2026-02-26', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00473', 'Retraining', '2025-09-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00321', 'Retraining', '2026-04-06', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00205', 'Safety Coaching', '2026-01-10', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00029', 'Safety Coaching', '2025-07-06', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00153', 'Licence Review', '2025-07-11', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00122', 'Safety Coaching', '2025-08-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00265', 'Safety Coaching', '2026-06-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00253', 'Retraining', '2025-11-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00263', 'Licence Review', '2025-08-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00057', 'Licence Review', '2025-12-01', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00297', 'Retraining', '2025-12-11', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00479', 'Licence Review', '2025-09-30', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00331', 'Safety Coaching', '2025-10-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00062', 'Licence Review', '2025-12-09', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00341', 'Retraining', '2026-05-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00247', 'Licence Review', '2025-09-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00471', 'Retraining', '2026-05-06', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00493', 'Retraining', '2025-10-29', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00344', 'Safety Coaching', '2026-06-24', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00309', 'Licence Review', '2026-05-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00174', 'Retraining', '2025-12-01', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00072', 'Licence Review', '2025-10-27', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00052', 'Retraining', '2026-03-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00218', 'Retraining', '2026-05-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00493', 'Retraining', '2026-02-18', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00422', 'Licence Review', '2026-01-22', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00349', 'Licence Review', '2025-10-15', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00407', 'Safety Coaching', '2026-02-08', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00403', 'Licence Review', '2026-02-18', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00397', 'Safety Coaching', '2026-04-05', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00335', 'Safety Coaching', '2025-12-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00116', 'Retraining', '2026-02-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00431', 'Licence Review', '2025-11-10', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00366', 'Retraining', '2025-12-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00096', 'Retraining', '2025-07-13', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00014', 'Retraining', '2026-03-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00316', 'Safety Coaching', '2025-07-18', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00461', 'Retraining', '2025-08-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00276', 'Safety Coaching', '2026-01-16', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00310', 'Retraining', '2026-01-03', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00324', 'Safety Coaching', '2025-12-11', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00031', 'Safety Coaching', '2026-04-26', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00146', 'Safety Coaching', '2025-12-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00448', 'Licence Review', '2026-04-16', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00326', 'Licence Review', '2026-06-21', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00112', 'Retraining', '2025-07-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00355', 'Safety Coaching', '2025-12-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00464', 'Safety Coaching', '2026-06-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00066', 'Licence Review', '2026-01-30', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00064', 'Safety Coaching', '2026-01-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00175', 'Safety Coaching', '2025-11-16', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00179', 'Licence Review', '2026-06-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00089', 'Safety Coaching', '2025-11-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00410', 'Retraining', '2025-07-23', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00228', 'Retraining', '2025-12-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00365', 'Safety Coaching', '2025-12-09', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00105', 'Licence Review', '2025-12-18', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00243', 'Retraining', '2026-03-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00106', 'Safety Coaching', '2026-03-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00359', 'Safety Coaching', '2026-05-02', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00480', 'Retraining', '2026-02-21', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00484', 'Retraining', '2026-05-23', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00466', 'Licence Review', '2025-09-20', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00435', 'Safety Coaching', '2025-07-02', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00124', 'Retraining', '2025-10-12', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00297', 'Retraining', '2025-11-15', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00149', 'Licence Review', '2026-06-11', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00198', 'Licence Review', '2026-06-04', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00481', 'Retraining', '2025-10-05', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00121', 'Licence Review', '2026-05-18', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00185', 'Retraining', '2025-08-23', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00061', 'Licence Review', '2025-08-31', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00206', 'Safety Coaching', '2025-09-16', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00056', 'Licence Review', '2026-04-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00247', 'Licence Review', '2025-08-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00408', 'Retraining', '2025-08-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00036', 'Licence Review', '2025-08-04', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00173', 'Safety Coaching', '2026-05-24', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00272', 'Retraining', '2025-10-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00024', 'Safety Coaching', '2026-04-26', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00157', 'Safety Coaching', '2025-08-13', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00040', 'Licence Review', '2026-05-19', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00094', 'Retraining', '2025-12-06', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00288', 'Licence Review', '2026-01-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00331', 'Safety Coaching', '2026-01-13', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00230', 'Licence Review', '2026-01-08', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00013', 'Safety Coaching', '2025-07-19', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00213', 'Retraining', '2026-01-01', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00066', 'Retraining', '2025-11-07', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00032', 'Retraining', '2026-05-28', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00137', 'Safety Coaching', '2025-08-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00276', 'Safety Coaching', '2026-01-03', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00300', 'Safety Coaching', '2025-10-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00218', 'Licence Review', '2026-05-24', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00349', 'Licence Review', '2026-02-10', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00359', 'Retraining', '2025-12-25', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00323', 'Retraining', '2026-06-01', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00442', 'Licence Review', '2026-05-11', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00198', 'Retraining', '2026-06-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00203', 'Retraining', '2025-11-02', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00080', 'Retraining', '2025-11-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00451', 'Retraining', '2025-11-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00102', 'Safety Coaching', '2026-06-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00413', 'Safety Coaching', '2026-03-25', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00397', 'Licence Review', '2025-12-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00207', 'Licence Review', '2025-07-04', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00468', 'Safety Coaching', '2025-07-18', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00056', 'Retraining', '2025-08-15', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00314', 'Safety Coaching', '2026-06-09', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00313', 'Retraining', '2025-12-28', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00229', 'Safety Coaching', '2025-10-06', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00445', 'Retraining', '2025-09-09', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00494', 'Retraining', '2026-05-19', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00255', 'Retraining', '2026-04-08', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00135', 'Licence Review', '2026-04-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00136', 'Safety Coaching', '2025-09-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00230', 'Retraining', '2026-04-19', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00056', 'Retraining', '2025-10-10', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00142', 'Safety Coaching', '2025-11-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00104', 'Safety Coaching', '2026-02-10', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00141', 'Safety Coaching', '2026-01-12', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00242', 'Retraining', '2025-07-08', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00288', 'Licence Review', '2026-04-24', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00156', 'Retraining', '2025-09-26', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00300', 'Safety Coaching', '2026-03-15', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00306', 'Safety Coaching', '2026-06-24', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00314', 'Safety Coaching', '2026-03-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00492', 'Licence Review', '2026-04-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00074', 'Licence Review', '2026-01-09', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00320', 'Retraining', '2026-05-24', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00366', 'Retraining', '2025-10-25', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00136', 'Safety Coaching', '2025-10-06', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00220', 'Licence Review', '2025-11-20', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00481', 'Safety Coaching', '2025-11-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00294', 'Safety Coaching', '2025-08-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00066', 'Retraining', '2026-04-04', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00294', 'Safety Coaching', '2025-11-03', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00299', 'Licence Review', '2025-11-24', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00225', 'Licence Review', '2025-10-07', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00476', 'Safety Coaching', '2025-08-12', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00445', 'Safety Coaching', '2025-10-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00222', 'Retraining', '2025-09-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00328', 'Safety Coaching', '2025-11-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00018', 'Retraining', '2026-03-29', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00083', 'Retraining', '2025-07-16', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00427', 'Licence Review', '2026-02-08', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00148', 'Retraining', '2025-07-27', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00030', 'Retraining', '2025-07-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00194', 'Retraining', '2026-03-12', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00462', 'Safety Coaching', '2025-07-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00103', 'Retraining', '2025-07-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00233', 'Licence Review', '2026-05-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00186', 'Licence Review', '2025-09-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00022', 'Licence Review', '2026-03-14', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00089', 'Retraining', '2025-11-18', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00054', 'Safety Coaching', '2025-10-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00260', 'Licence Review', '2026-03-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00382', 'Retraining', '2026-05-18', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00392', 'Safety Coaching', '2026-02-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00356', 'Retraining', '2025-09-05', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00278', 'Safety Coaching', '2025-08-22', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00327', 'Licence Review', '2026-01-23', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00415', 'Safety Coaching', '2026-02-08', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00179', 'Retraining', '2025-12-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00462', 'Licence Review', '2025-10-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00198', 'Safety Coaching', '2025-10-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00262', 'Licence Review', '2025-07-07', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00088', 'Retraining', '2025-07-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00082', 'Licence Review', '2026-03-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00055', 'Licence Review', '2026-02-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00007', 'Licence Review', '2026-02-02', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00037', 'Licence Review', '2026-04-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00216', 'Licence Review', '2025-11-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00450', 'Retraining', '2026-06-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00131', 'Licence Review', '2025-10-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00320', 'Safety Coaching', '2025-08-07', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00289', 'Retraining', '2026-03-12', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00493', 'Safety Coaching', '2026-05-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00101', 'Safety Coaching', '2025-07-29', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00171', 'Licence Review', '2026-04-03', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00157', 'Safety Coaching', '2025-09-30', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00396', 'Retraining', '2025-09-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00008', 'Licence Review', '2026-04-16', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00370', 'Licence Review', '2025-12-06', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00255', 'Licence Review', '2026-02-21', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00387', 'Licence Review', '2026-02-06', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00453', 'Safety Coaching', '2025-08-02', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00431', 'Retraining', '2026-01-31', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00231', 'Safety Coaching', '2025-12-11', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00314', 'Safety Coaching', '2026-02-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00081', 'Licence Review', '2026-03-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00247', 'Safety Coaching', '2025-12-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00017', 'Safety Coaching', '2025-08-06', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00376', 'Safety Coaching', '2026-03-17', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00449', 'Licence Review', '2026-03-06', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00350', 'Licence Review', '2025-11-07', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00294', 'Safety Coaching', '2025-10-07', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00187', 'Safety Coaching', '2026-02-08', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00342', 'Safety Coaching', '2026-03-21', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00129', 'Retraining', '2025-08-03', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00397', 'Retraining', '2026-04-14', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00251', 'Licence Review', '2025-08-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00184', 'Retraining', '2026-03-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00053', 'Retraining', '2026-04-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00147', 'Safety Coaching', '2025-10-25', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00113', 'Retraining', '2026-01-14', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00172', 'Retraining', '2025-08-09', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00476', 'Safety Coaching', '2025-09-01', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00094', 'Licence Review', '2026-06-10', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00082', 'Safety Coaching', '2026-04-14', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00307', 'Safety Coaching', '2025-10-11', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00350', 'Licence Review', '2026-02-12', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00126', 'Retraining', '2025-10-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00022', 'Retraining', '2025-11-17', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00047', 'Retraining', '2026-06-08', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00026', 'Retraining', '2025-08-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00375', 'Retraining', '2026-03-24', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00127', 'Retraining', '2025-08-18', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00230', 'Licence Review', '2026-06-15', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00287', 'Retraining', '2025-09-13', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00397', 'Safety Coaching', '2026-03-20', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00347', 'Safety Coaching', '2026-03-23', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00056', 'Safety Coaching', '2025-12-28', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00106', 'Licence Review', '2025-07-26', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00118', 'Licence Review', '2026-06-15', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00489', 'Licence Review', '2025-09-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00483', 'Retraining', '2025-12-07', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00186', 'Safety Coaching', '2026-05-15', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00037', 'Retraining', '2025-11-12', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00168', 'Safety Coaching', '2026-03-09', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00194', 'Retraining', '2025-11-14', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00162', 'Licence Review', '2025-10-05', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00050', 'Retraining', '2026-04-26', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00113', 'Safety Coaching', '2026-02-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00015', 'Safety Coaching', '2025-12-19', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00016', 'Retraining', '2025-09-30', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00097', 'Licence Review', '2026-07-01', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00104', 'Retraining', '2026-02-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00119', 'Licence Review', '2025-09-29', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00226', 'Safety Coaching', '2026-06-09', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00452', 'Retraining', '2025-12-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00395', 'Retraining', '2025-11-17', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00079', 'Licence Review', '2026-03-28', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00492', 'Licence Review', '2025-12-23', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00392', 'Retraining', '2025-11-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00017', 'Retraining', '2026-02-19', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00084', 'Retraining', '2026-06-13', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00270', 'Retraining', '2025-11-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00347', 'Licence Review', '2025-08-18', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00363', 'Safety Coaching', '2026-01-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00490', 'Retraining', '2025-09-22', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00472', 'Retraining', '2025-12-08', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00039', 'Retraining', '2025-11-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00177', 'Retraining', '2026-05-19', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00402', 'Retraining', '2026-02-14', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00102', 'Licence Review', '2025-09-03', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00132', 'Retraining', '2026-06-06', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00117', 'Retraining', '2026-05-03', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00030', 'Licence Review', '2025-12-19', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00038', 'Safety Coaching', '2026-05-17', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00140', 'Safety Coaching', '2026-06-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00137', 'Licence Review', '2026-05-27', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00377', 'Retraining', '2025-10-19', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00069', 'Licence Review', '2025-09-25', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00104', 'Licence Review', '2026-03-22', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00320', 'Safety Coaching', '2025-12-12', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00138', 'Safety Coaching', '2025-08-09', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00453', 'Safety Coaching', '2025-07-29', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00028', 'Safety Coaching', '2025-07-21', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00187', 'Licence Review', '2026-01-10', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00057', 'Safety Coaching', '2025-07-12', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00226', 'Licence Review', '2026-01-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00076', 'Safety Coaching', '2026-02-20', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00335', 'Retraining', '2026-06-08', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00227', 'Safety Coaching', '2025-08-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00025', 'Licence Review', '2026-03-29', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00096', 'Safety Coaching', '2025-07-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00357', 'Safety Coaching', '2025-07-09', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00439', 'Retraining', '2025-10-04', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00377', 'Safety Coaching', '2026-01-26', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00202', 'Safety Coaching', '2025-09-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00045', 'Licence Review', '2026-05-04', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00153', 'Licence Review', '2026-02-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00228', 'Retraining', '2026-06-02', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00297', 'Retraining', '2026-03-22', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00102', 'Licence Review', '2025-10-29', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00337', 'Retraining', '2025-09-01', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00050', 'Retraining', '2026-02-01', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00119', 'Licence Review', '2026-04-03', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00019', 'Licence Review', '2026-04-01', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00037', 'Retraining', '2025-07-06', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00426', 'Licence Review', '2026-01-05', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00476', 'Licence Review', '2026-02-17', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00395', 'Licence Review', '2026-03-31', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00234', 'Safety Coaching', '2025-12-24', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00493', 'Licence Review', '2026-05-09', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00434', 'Licence Review', '2025-11-16', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00226', 'Safety Coaching', '2026-02-28', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00495', 'Retraining', '2026-01-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00225', 'Safety Coaching', '2026-03-25', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00135', 'Safety Coaching', '2025-09-10', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00303', 'Safety Coaching', '2025-11-24', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00223', 'Licence Review', '2025-08-04', 'In Progress');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00360', 'Licence Review', '2026-01-31', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00187', 'Retraining', '2026-02-23', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00172', 'Retraining', '2026-02-22', 'Failed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00267', 'Safety Coaching', '2026-06-26', 'Pending');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00400', 'Licence Review', '2026-05-03', 'Passed');
insert into CoachingRecord (DriverID, CoachingType, Date, Outcome) values ('DRV00244', 'Licence Review', '2025-08-27', 'Pending');
