insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Zesty Garlic Marinade', 'Integer a nibh. In quis justo.', 464, 39, 15647);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Mouse', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 446, 24, 30887);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cotton Pajama Set', 'Mauris ullamcorper purus sit amet nulla.', 381, 67, 57715);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Strawberry Banana Smoothie Pack', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 488, 20, 56203);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Outdoor Portable Fire Pit', 'Aenean fermentum.', 341, 59, 33876);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cucumber', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 380, 48, 12791);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mechanical Keyboard', 'Quisque ut erat. Curabitur gravida nisi at nibh.', 151, 32, 22974);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Laundry Bag', 'Pellentesque viverra pede ac diam.', 372, 25, 89840);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Nail Clipper', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 344, 36, 56404);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Compact Shoe Rack', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 333, 55, 85028);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Avocado Oil Mayo', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 342, 33, 14865);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Balsamic Salad Dressing', 'Duis aliquam convallis nunc.', 477, 17, 50562);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Griddle', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 429, 67, 21120);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Hiking Gaiters', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 470, 5, 74589);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Classic BBQ Sauce', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 193, 17, 71401);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Safety Goggles', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 182, 9, 87660);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garden Vegetable Chips', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 96, 53, 25597);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Italian Herbal Seasoning', 'Phasellus id sapien in sapien iaculis congue.', 242, 75, 71287);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Butter Cookies', 'Etiam vel augue.', 94, 72, 51723);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Milk Ice Cream', 'Vivamus in felis eu sapien cursus vestibulum.', 386, 53, 3518);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Microfiber Cleaning Cloths', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.', 419, 18, 8748);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wooden Kitchen Utensil Set', 'Nunc nisl.', 229, 29, 40403);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Korma', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 81, 63, 18322);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mayonnaise', 'Donec dapibus. Duis at velit eu est congue elementum.', 244, 41, 16053);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sushi Roll Kit', 'Nullam varius.', 157, 58, 24536);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sweet Chili Sauce', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 410, 31, 27933);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Animal Paw Print Soap Dispenser', 'In congue. Etiam justo.', 212, 42, 80551);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Laptop Desk', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 86, 57, 36080);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garden Vegetable Chips', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 107, 42, 5109);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dried Cranberries', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 470, 32, 68252);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Classic Beef Chili', 'Aenean sit amet justo. Morbi ut odio.', 165, 21, 72786);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Herb Seasoned Couscous', 'Maecenas ut massa quis augue luctus tincidunt.', 115, 66, 15316);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mashed Sweet Potatoes', 'In sagittis dui vel nisl. Duis ac nibh.', 46, 56, 62226);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Makeup Organizer', 'Quisque ut erat.', 265, 43, 52803);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Banana Peanut Butter Smoothie', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 364, 21, 46639);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Creamy Avocado Dip', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 167, 16, 76591);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pepperoni Pizza Roll-Ups', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 167, 37, 63452);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Roasted Peanuts', 'Integer ac neque.', 39, 28, 25625);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wine Glasses', 'Curabitur in libero ut massa volutpat convallis.', 152, 41, 3471);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pasta Primavera', 'Curabitur at ipsum ac tellus semper interdum.', 370, 26, 14403);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smartphone Holder for Car', 'Praesent lectus.', 226, 19, 10060);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Stuffed Peppers with Quinoa', 'Sed vel enim sit amet nunc viverra dapibus.', 328, 16, 52924);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan chocolate chip cookies', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 135, 56, 20774);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Bike', 'Curabitur at ipsum ac tellus semper interdum.', 253, 20, 7763);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Zesty Garlic Marinade', 'Phasellus sit amet erat. Nulla tempus.', 35, 68, 5705);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Bed with Removable Cover', 'Morbi a ipsum.', 246, 46, 54931);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Mouse', 'Donec semper sapien a libero. Nam dui.', 441, 46, 41939);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Multifunctional Baby Bottle Warmer', 'Morbi vel lectus in quam fringilla rhoncus.', 66, 33, 32591);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan Taco Seasoning', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 205, 39, 11486);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Garlic Shrimp', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 195, 67, 24159);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Instant Mashed Potatoes', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 142, 43, 67489);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smartphone Tripod', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 376, 25, 38404);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Salsa', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 499, 59, 47922);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peanut Butter Protein Balls', 'Nulla tellus.', 142, 69, 66728);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Computer Monitor Stand', 'Nulla nisl. Nunc nisl.', 30, 51, 89124);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pasta Maker', 'Donec vitae nisi.', 498, 23, 61760);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Griddle with Removable Plates', 'Sed ante. Vivamus tortor.', 37, 45, 9219);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Baked Falafel Balls', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 439, 33, 60758);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ripped Boyfriend Jeans', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 156, 67, 78279);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whole Wheat Pasta', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 194, 37, 16847);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cheddar Cheese Slices', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 289, 29, 27459);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mechanical Keyboard', 'Suspendisse accumsan tortor quis turpis. Sed ante.', 223, 65, 35276);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Deluxe First Aid Kit', 'Nulla mollis molestie lorem. Quisque ut erat.', 315, 60, 55133);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sour Cream', 'Curabitur in libero ut massa volutpat convallis.', 234, 23, 65961);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sliced Ham', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 442, 59, 39744);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Electric Fan', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 443, 38, 41197);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sriracha Honey Glaze', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 339, 30, 85623);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Children''s Garden Tool Set', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 148, 34, 80706);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Hair Dryer', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 476, 73, 2577);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Creamy Spinach Dip', 'Vivamus tortor. Duis mattis egestas metus.', 390, 71, 60180);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Speakers', 'Nunc purus.', 346, 8, 8697);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dog Training Whistle', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 257, 60, 16402);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Graham Crackers', 'Aenean sit amet justo.', 414, 70, 1581);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Car Vacuum Cleaner', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 393, 69, 19746);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Food Storage Container', 'Integer ac neque. Duis bibendum.', 125, 48, 64225);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Biodegradable Trash Bags', 'In hac habitasse platea dictumst.', 37, 25, 58116);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magnetic Spice Containers', 'Curabitur convallis.', 275, 17, 81497);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Stainless Steel Grater', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 429, 56, 45421);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Spinach', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 429, 50, 36738);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Foam Muscle Roller', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 261, 52, 32666);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Toy Building Set', 'Sed sagittis.', 484, 72, 12349);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Ice Maker', 'Nulla tempus.', 130, 68, 68816);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Blackberry Compote', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 344, 11, 8065);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peanut Butter', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 40, 32, 54616);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Crispy Rice Treats', 'Praesent blandit.', 396, 31, 24597);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Spicy Chicken Wings', 'Maecenas rhoncus aliquam lacus.', 215, 62, 85771);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Microfiber Cleaning Cloths', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 430, 29, 23898);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fresh Basil', 'Nam tristique tortor eu pede.', 273, 34, 35782);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Memory Foam Mattress Topper', 'Vivamus in felis eu sapien cursus vestibulum.', 273, 12, 32185);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Whole Wheat Flour', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 268, 42, 56993);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Personal Blender with Travel Lid', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 70, 16, 70737);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Breakfast Sausage', 'Curabitur convallis.', 210, 29, 59017);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garden Hose', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 333, 50, 28247);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Elderberry Syrup Kit', 'Cras pellentesque volutpat dui.', 24, 70, 70197);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whole Grain Hamburger Buns', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 494, 18, 87292);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Teriyaki Chicken Skewers', 'Vivamus vel nulla eget eros elementum pellentesque.', 230, 34, 82473);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Nut Cheerios', 'Phasellus sit amet erat. Nulla tempus.', 433, 52, 64682);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coffee Subscription Service', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 70, 38, 24485);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Jennifer''s Amazing Lip Balm Kit', 'Aenean fermentum.', 11, 53, 83894);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tortilla Chips', 'Pellentesque ultrices mattis odio.', 47, 43, 79600);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Lightweight Rain Jacket', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 327, 58, 69809);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Water Fountain', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 387, 72, 43843);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Mushroom Risotto', 'Nulla tellus.', 296, 21, 87970);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pineapple Salsa', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 171, 31, 21859);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Repair Tool Set for Home Improvement', 'Mauris lacinia sapien quis libero.', 255, 74, 61533);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mini Indoor Herb Garden Kit', 'Nunc purus. Phasellus in felis.', 124, 47, 25081);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Kneeling Pad', 'Morbi vel lectus in quam fringilla rhoncus.', 155, 7, 39807);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Air Fryer', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 187, 54, 27531);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whipped Cream Cheese', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 296, 23, 60199);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Brownie Bites', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 17, 16, 34246);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Grill Cover', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 145, 16, 75913);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ceramic Non-Stick Frying Pan', 'Cras non velit nec nisi vulputate nonummy.', 272, 65, 86288);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Bamboo Charcoal Air Purifier Bags', 'Etiam pretium iaculis justo.', 278, 55, 46058);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Spicy Avocado Salsa', 'Aenean lectus.', 499, 23, 72354);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Egg Noodles', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 356, 54, 12498);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Yoga Strap', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 103, 35, 48736);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Air Compressor', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 218, 64, 20628);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Butter Popcorn', 'Sed ante.', 499, 65, 72826);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Microfiber Cleaning Cloth Set', 'In hac habitasse platea dictumst.', 220, 47, 66533);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Thai Basil Fried Rice', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 423, 10, 73996);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Lemon Pepper Seasoning', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 21, 52, 66493);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sweet Potato Chips', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 289, 42, 43319);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Solar Power Bank', 'Sed accumsan felis.', 474, 36, 42286);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Size Toiletry Bottles', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 314, 73, 36023);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Crunch Granola Bars', 'Praesent blandit. Nam nulla.', 138, 41, 42446);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garlic Herb Cream Cheese', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 329, 30, 69809);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chia Seed Pudding Mix', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 312, 7, 8400);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Desk Organizer Set', 'Integer a nibh.', 343, 11, 30135);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Makeup Organizer', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 86, 8, 18853);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Ice Maker', 'Cras in purus eu magna vulputate luctus.', 437, 63, 85599);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wrist Support Brace', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 210, 59, 71371);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garden Tool Set with Carrying Bag', 'Mauris sit amet eros.', 142, 69, 49580);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magnetic Whiteboard', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 430, 41, 17920);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dual Function Electric Skillet', 'Suspendisse potenti.', 273, 35, 64618);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dog Waste Bag Dispenser', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 112, 36, 58487);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fruit Infuser Water Bottle', 'Integer tincidunt ante vel ipsum.', 129, 55, 24493);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mango Chunks', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 291, 53, 36005);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Black Bean Burger', 'Donec dapibus.', 385, 55, 28608);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chunky Knit Sweater', 'Quisque porta volutpat erat.', 294, 26, 41662);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Hammock Swing', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 48, 29, 38529);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sturdy Bookends', 'Praesent blandit lacinia erat.', 53, 61, 49278);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Thai Peanut Dressing', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 362, 10, 50857);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Streaming Device', 'Morbi porttitor lorem id ligula.', 135, 70, 82557);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Bike', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 251, 40, 18155);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sun-Dried Tomatoes', 'Cras in purus eu magna vulputate luctus.', 169, 11, 22504);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sweet Potato Noodles', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 385, 23, 54698);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Patterned Knit Scarf', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 183, 19, 16543);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Beach Cover-Up', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 296, 51, 70779);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Curry Sauce', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 413, 11, 41524);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Granola', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 399, 12, 86348);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Stylish Wide-Leg Trousers', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 277, 18, 40254);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Knitted Infinity Scarf', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 288, 20, 21425);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Eggs (dozen)', 'Etiam pretium iaculis justo.', 36, 13, 49470);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cranberry Orange Juice', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', 150, 43, 25790);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('LED Camping Lantern with USB Charging', 'In blandit ultrices enim.', 63, 46, 69891);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Keyboard and Mouse Combo', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 333, 41, 18364);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garden Kneeler and Seat', 'Praesent id massa id nisl venenatis lacinia.', 35, 37, 9133);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sweet BBQ Dipping Sauce', 'Integer a nibh. In quis justo.', 351, 66, 26311);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Folding Exercise Bike', 'In congue.', 384, 75, 54574);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Thai Coconut Curry Sauce', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 140, 43, 3235);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Chipotle Glaze', 'Curabitur in libero ut massa volutpat convallis.', 213, 66, 21124);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Butter Popcorn', 'Integer a nibh. In quis justo.', 261, 69, 73764);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Oatmeal', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 469, 33, 42758);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Massage Gun', 'Donec dapibus.', 463, 55, 80674);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Survival Gear Kit', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 486, 43, 65751);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Laptop Desk', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 162, 29, 46980);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Jump Starter', 'Nulla tempus.', 19, 59, 67072);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Classic Cheeseburger Mix', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 94, 42, 1249);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Air Pump', 'Quisque porta volutpat erat.', 131, 18, 77091);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Charger', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 239, 49, 23122);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Personal Security Alarm Keychain', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 487, 7, 40954);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Earbuds', 'In sagittis dui vel nisl.', 92, 50, 35630);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Yoga Mat Strap', 'Nam tristique tortor eu pede.', 392, 19, 40083);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('A-Line Skirt', 'Nullam varius. Nulla facilisi.', 287, 31, 75935);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Butternut Squash Ravioli', 'Nullam porttitor lacus at turpis.', 478, 52, 7702);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('DIY Candle Making Kit', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 289, 33, 58180);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Earbuds', 'Aliquam sit amet diam in magna bibendum imperdiet.', 162, 27, 9815);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ready-to-Eat Chili', 'Etiam vel augue.', 381, 65, 61367);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chilli Lime Corn on the Cob', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 51, 52, 30273);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Eco-Friendly Cleaning Cloths', 'Morbi a ipsum. Integer a nibh.', 79, 72, 36580);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Folding Table', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 343, 60, 19272);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tactical Backpack', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 156, 56, 44847);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Jennifer''s Amazing Lip Balm Kit', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 268, 6, 71456);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Heating Pad', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 441, 16, 4983);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Quinoa Pudding', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', 429, 14, 29352);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Leather Crossbody Bag', 'Nunc nisl.', 485, 34, 34466);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pecan Nuts', 'Nulla justo.', 440, 40, 63378);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Legging Pants', 'Etiam justo. Etiam pretium iaculis justo.', 384, 30, 65186);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Siphon Coffee Maker', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 499, 25, 79283);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Canvas High-Top Sneakers', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 356, 75, 51735);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cream Cheese', 'Suspendisse accumsan tortor quis turpis.', 158, 21, 30868);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Linen Trousers', 'Sed sagittis.', 82, 24, 85596);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Overnight Hiking Backpack', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 78, 52, 22387);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Hash Browns', 'In hac habitasse platea dictumst.', 426, 58, 3139);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Strawberry Rhubarb Jam', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 218, 48, 3855);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peach Slices (canned)', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 199, 26, 34588);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Coconut Water', 'Nulla mollis molestie lorem. Quisque ut erat.', 495, 17, 22545);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tofu', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 80, 66, 68689);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Rice Cakes', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 381, 15, 43577);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Canned Black Beans', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 100, 49, 73792);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Crunch Granola Bars', 'Sed accumsan felis.', 22, 47, 56680);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Glass Food Containers', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.', 343, 57, 28734);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Knife', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 145, 58, 50878);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Grooming Brush', 'Aenean lectus.', 419, 59, 4748);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('LED Under Cabinet Lighting', 'Integer non velit.', 414, 6, 31181);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Yoga Strap', 'Pellentesque at nulla. Suspendisse potenti.', 251, 48, 67367);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Safety Belt for Car', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 177, 69, 9136);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Herb-Infused Olive Oil', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.', 298, 49, 61525);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Spicy Italian Sausage', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 270, 74, 29787);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chicken Sausage', 'In quis justo. Maecenas rhoncus aliquam lacus.', 461, 50, 68454);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Pecan Oatmeal Cookies', 'Nulla tellus. In sagittis dui vel nisl.', 212, 63, 86293);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('High-Speed Blender', 'Nam tristique tortor eu pede.', 100, 61, 29443);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Beef Jerky', 'Nunc purus. Phasellus in felis.', 87, 62, 15162);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('LED Flashing Pet Collar', 'Etiam justo.', 254, 22, 68687);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Standing Desk', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 198, 75, 19003);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Olive Oil', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 329, 57, 18623);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Acai Bowl', 'Morbi porttitor lorem id ligula.', 306, 67, 80076);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Oatmeal', 'Donec posuere metus vitae ipsum. Aliquam non mauris.', 22, 61, 64418);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Hand Mixer', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 498, 14, 64060);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Edamame', 'Proin risus. Praesent lectus.', 285, 28, 80176);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Roasted Garlic Mashed Potatoes', 'Aliquam erat volutpat. In congue.', 224, 72, 42127);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Almond Granola', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 185, 62, 80547);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Paprika', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 116, 42, 31537);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cat Scratching Post with Toys', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 181, 13, 73150);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Multi-Function Meat Tenderizer', 'Cras non velit nec nisi vulputate nonummy.', 125, 51, 83942);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Digital Food Thermometer', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 454, 14, 47461);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Griddle with Removable Plates', 'Suspendisse accumsan tortor quis turpis.', 46, 71, 32975);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Patterned Knit Scarf', 'Maecenas rhoncus aliquam lacus.', 203, 17, 76432);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Plaid Flannel Shirt', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 290, 67, 57059);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Pet Stroller', 'In eleifend quam a odio.', 366, 39, 75251);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magic Color-Changing Mug', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 254, 54, 31079);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Butter', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 123, 35, 65439);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smartphone Gimbal', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 49, 56, 15187);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Grilled Vegetable Medley', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 443, 22, 36821);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Homemade Salsa', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 134, 64, 45415);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Lemon Dill Chicken Skewers', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 93, 23, 34983);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smartphone Stand', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 132, 15, 42156);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Karaoke Microphone', 'Vestibulum rutrum rutrum neque.', 189, 61, 4705);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan Mac & Cheese', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 492, 60, 45591);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Oven-Baked Parmesan Zucchini', 'Mauris sit amet eros.', 121, 67, 65337);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wall-Mounted Spice Rack', 'Aenean fermentum.', 64, 42, 13712);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Kid''s Fruit Snacks', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 390, 72, 60466);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Orthopedic Pillow', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 160, 5, 29166);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Sushi Rolls', 'Quisque ut erat.', 31, 31, 87399);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smart Plant Monitor', 'Duis at velit eu est congue elementum.', 465, 45, 9442);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Two-Tier Fruit Basket', 'Phasellus id sapien in sapien iaculis congue.', 405, 46, 17815);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable UV Sterilizer', 'Vivamus in felis eu sapien cursus vestibulum.', 43, 49, 24473);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Comfy Slippers', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 301, 20, 58224);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Granola Clusters', 'Nullam sit amet turpis elementum ligula vehicula consequat.', 19, 73, 14755);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Trendy Bomber Jacket', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 13, 62, 28235);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Feta Cheese Crumbles', 'Nunc nisl.', 380, 48, 13677);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Sesame Chicken Mix', 'Nullam molestie nibh in lectus.', 433, 72, 69826);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Car Phone Mount', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.', 332, 26, 60817);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garlic and Herb Cream Cheese', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.', 104, 43, 2550);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Bamboo Cotton Tank Top', 'Nullam varius.', 246, 68, 8239);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Printer', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 205, 57, 75879);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('A-Line Skirt', 'Suspendisse potenti.', 337, 15, 89539);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Digital Drawing Tablet', 'Ut tellus.', 139, 58, 58321);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Rice Pilaf Mix', 'Donec dapibus.', 414, 43, 86917);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cucumber', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 58, 59, 72063);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('USB-C Hub', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.', 494, 23, 32875);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Phone Mug Holder', 'Sed accumsan felis.', 415, 61, 62052);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Green Lentils', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 82, 58, 63745);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fitness Resistance Bands Set', 'Nulla tellus.', 422, 70, 66298);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pumpkin Spice Pancake Mix', 'Nulla suscipit ligula in lacus.', 362, 5, 37362);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Infrared Thermometer Gun', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 221, 50, 64958);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable SSD', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 90, 49, 78636);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Non-Stick Baking Sheet', 'Integer ac neque. Duis bibendum.', 119, 5, 35291);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Scent Diffuser', 'Nunc rhoncus dui vel sem. Sed sagittis.', 177, 36, 47689);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cranberry Almond Granola', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 181, 59, 33780);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Safety First Aid Kit', 'In hac habitasse platea dictumst.', 160, 11, 52839);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Comfort Flats', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 169, 46, 24136);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Fried Rice Mix', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 338, 25, 60434);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garlic Herb Grilled Chicken', 'Duis aliquam convallis nunc.', 456, 67, 17797);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sweet Corn Fritters', 'Sed sagittis.', 267, 52, 78480);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Training Clicker', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 472, 30, 28386);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Digital Food Scale', 'Nunc purus. Phasellus in felis.', 444, 73, 75162);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Herb-Infused Olive Oil', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 77, 38, 62840);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Heavy-Duty Utility Tote', 'Integer non velit.', 114, 54, 43285);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Water Fountain', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 13, 42, 16625);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Roasted Chickpeas', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 405, 36, 83178);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Buttermilk Pancakes', 'Vivamus tortor. Duis mattis egestas metus.', 183, 38, 77346);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mini Air Hockey Table', 'Duis bibendum.', 486, 64, 60023);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magnet Travel Fridge Magnets', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 299, 40, 42209);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sesame Ginger Dressing', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 19, 41, 23773);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Food Steamer', 'Vivamus vestibulum sagittis sapien.', 230, 63, 68463);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pineapple Teriyaki Chicken Mix', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 412, 62, 69208);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Protein Bar Variety Pack', 'Vestibulum ac est lacinia nisi venenatis tristique.', 359, 74, 12588);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Bacon Popcorn', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 254, 23, 86517);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smart Plant Monitor', 'Aliquam non mauris. Morbi non lectus.', 294, 12, 41955);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Multi-Purpose Plant Care Tool', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 334, 29, 11797);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ski Goggles', 'Quisque ut erat.', 291, 39, 42433);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tahini', 'In sagittis dui vel nisl.', 131, 33, 42482);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Green Tea', 'Aliquam erat volutpat. In congue.', 409, 19, 55801);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tactical Backpack', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 447, 31, 76794);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sliced Cheese', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 318, 11, 24375);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Scent Diffuser Oil', 'Aliquam erat volutpat. In congue.', 405, 18, 68674);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garlic Naan Bread', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 148, 8, 3180);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Berry Blend', 'Pellentesque at nulla.', 20, 52, 80071);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Compressible Packing Cubes', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 357, 54, 50773);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Window Bird Feeder', 'Integer a nibh. In quis justo.', 227, 11, 5004);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cinnamon Raisin Bagels', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 303, 59, 70082);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Beef Chili', 'Quisque ut erat.', 44, 68, 23391);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Gaming Mouse', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 340, 17, 11770);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Personal Blender with Cups', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', 171, 74, 64193);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pumpkin Pancake Mix', 'Nunc nisl.', 199, 31, 2527);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wooden Toy Train Set', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 152, 9, 17863);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chicken Breasts', 'Pellentesque eget nunc.', 379, 8, 18476);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Tomato Soup', 'Phasellus in felis.', 279, 70, 68088);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Size Toiletry Bottles', 'Integer ac neque. Duis bibendum.', 148, 38, 41847);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fitness Tracker with Heart Rate Monitor', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 258, 32, 9083);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Air Compressor', 'Phasellus in felis. Donec semper sapien a libero.', 401, 75, 8431);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Berry Medley', 'Ut tellus.', 471, 30, 40703);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Berries Medley', 'Maecenas pulvinar lobortis est.', 28, 50, 32437);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Lime Rice', 'Donec ut dolor.', 55, 58, 26630);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peanut Butter Banana Smoothie', 'Proin eu mi. Nulla ac enim.', 326, 29, 40146);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Oven-Baked Cheese Crisps', 'Fusce posuere felis sed lacus.', 133, 63, 9642);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Surimi Crab Sticks', 'In hac habitasse platea dictumst.', 344, 12, 19148);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless HDMI Transmitter', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 385, 47, 14884);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peach Slices (canned)', 'Etiam pretium iaculis justo.', 79, 42, 17195);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smart Thermostat', 'Vivamus in felis eu sapien cursus vestibulum.', 163, 16, 64255);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Earbuds', 'Aliquam quis turpis eget elit sodales scelerisque.', 350, 44, 66582);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chickpea Snack Mix', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 178, 26, 28017);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Inspirational Wall Art', 'Cras non velit nec nisi vulputate nonummy.', 416, 23, 48952);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Inflatable Pool Float', 'Fusce consequat. Nulla nisl.', 332, 22, 8800);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chocolate Dipped Fruit', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 380, 40, 26434);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Almond Butter', 'Nulla ut erat id mauris vulputate elementum.', 108, 12, 75784);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Bamboo Utensil Holder', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 233, 32, 11119);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peach Yogurt', 'Nullam molestie nibh in lectus.', 53, 42, 72107);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('High-Quality Yoga Mat', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 260, 40, 42205);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ginger Snaps', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 156, 15, 50167);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Avocado Oil Mayo', 'Sed ante.', 362, 51, 13372);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mini Indoor Herb Garden Kit', 'Etiam justo.', 214, 33, 27824);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cranberry Pecan Granola', 'Sed accumsan felis.', 323, 74, 33058);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Essential Oil Diffuser', 'Nam tristique tortor eu pede.', 314, 30, 75594);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magnetic Puzzle Board', 'Morbi non lectus.', 313, 58, 30989);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Mushroom Risotto', 'Phasellus id sapien in sapien iaculis congue.', 81, 15, 57202);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Spring Rolls', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 28, 42, 86433);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whipped Cream Cheese', 'Duis bibendum.', 347, 51, 78879);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Skincare Set', 'In blandit ultrices enim.', 225, 71, 83417);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Hot Dog Buns', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 25, 73, 73253);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pita Bread', 'Duis aliquam convallis nunc.', 349, 51, 10586);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Flour Biscuits', 'Proin at turpis a pede posuere nonummy.', 166, 70, 34686);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Solar Camp Shower', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 111, 51, 3681);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Buffalo Style Cauliflower Bites', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 297, 60, 22784);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('High-Pressure Handheld Shower Head', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 311, 44, 39950);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Paint By Numbers Kit', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 162, 31, 3293);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pomegranate Juice', 'Integer a nibh. In quis justo.', 399, 20, 26857);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whipped Cream Cheese', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 477, 71, 36538);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Gardening Gloves', 'In blandit ultrices enim.', 178, 24, 9693);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Marinara Sauce', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 377, 39, 66935);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Sweet Potatoes', 'Integer non velit.', 448, 56, 21419);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cranberry Almond Cookies', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 363, 64, 61743);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Graphic Print Leggings', 'Nulla justo.', 390, 71, 55177);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Resistance Bands', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 405, 23, 41058);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Zesty Cilantro Lime Dressing', 'Nam tristique tortor eu pede.', 320, 68, 67447);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Self-Massaging Pillow', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 396, 36, 72590);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chocolate Protein Powder', 'Nulla nisl. Nunc nisl.', 355, 48, 28946);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Classic Leather Wallet', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 252, 52, 45664);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Hair Vacuum Cleaner Attachment', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 125, 52, 11399);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Floral Summer Dress', 'Etiam pretium iaculis justo.', 249, 64, 32892);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Interactive Plush Toy', 'Morbi vel lectus in quam fringilla rhoncus.', 60, 14, 80957);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Balsamic Glazed Brussels Sprouts', 'Mauris sit amet eros.', 70, 66, 85975);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dark Chocolate Raisins', 'Nullam molestie nibh in lectus.', 30, 36, 26901);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ceramic Planter Set', 'Vestibulum rutrum rutrum neque.', 299, 60, 19246);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smart Thermostat with Wi-Fi', 'Nulla nisl. Nunc nisl.', 493, 56, 82877);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Protein Bar Variety Pack', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 193, 60, 51727);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('High-Speed HDMI Cable', 'Suspendisse potenti.', 102, 40, 83684);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Inflatable Party Cooler', 'Sed sagittis.', 433, 31, 2209);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Strawberry Banana Smoothie Pack', 'Phasellus in felis.', 457, 13, 64989);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Brazil Nuts', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 312, 25, 48508);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Whole Grain Oats', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 297, 40, 65180);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Hair Removal Roller', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 223, 18, 34198);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peach Preserves', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 454, 22, 67117);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sooji (Semolina)', 'Nam nulla.', 64, 26, 34931);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Maple Oatmeal', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 95, 28, 24444);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Falafel Mix', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 159, 71, 82373);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vanilla Almond Granola', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 440, 69, 84893);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Margherita Pizza', 'Morbi vel lectus in quam fringilla rhoncus.', 341, 46, 76296);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pepperoni Pizza Roll-Ups', 'Integer a nibh. In quis justo.', 394, 41, 64467);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Curry', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 301, 13, 73445);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Multi-Layer Food Steamer', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 110, 74, 73659);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Kids'' Outdoor Explorer Kit', 'Fusce consequat. Nulla nisl.', 306, 29, 652);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Suede Ankle Booties', 'Donec semper sapien a libero.', 375, 32, 60771);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless HDMI Receiver', 'Aenean fermentum.', 467, 27, 24539);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Creative Puzzle Game', 'Etiam faucibus cursus urna. Ut tellus.', 270, 7, 88709);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Peanut Butter', 'Aenean lectus. Pellentesque eget nunc.', 342, 30, 39837);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Outdoor Camping Lantern', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 132, 55, 61575);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Lemonade Mix', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 44, 34, 1778);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dog Training Whistle', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 334, 15, 67109);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Nutty Granola Clusters', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 21, 32, 28676);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan Chocolate Cake Mix', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 118, 35, 25403);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Basil Tomato Soup', 'Praesent blandit.', 194, 14, 19054);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan chocolate chip cookies', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 390, 34, 3291);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey Mustard Pretzel Bites', 'Integer ac leo.', 123, 73, 61513);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Teriyaki Beef Jerky', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 359, 66, 40963);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fruit and Nut Energy Bites', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 382, 65, 3383);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Car Vacuum Cleaner', 'Suspendisse accumsan tortor quis turpis.', 263, 46, 64845);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Hair Straightener', 'Maecenas pulvinar lobortis est.', 178, 64, 76627);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ceramic Non-Stick Frying Pan', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 369, 27, 69298);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Joy Bars', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 18, 51, 30527);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Butter Churn', 'Morbi quis tortor id nulla ultrices aliquet.', 196, 40, 48932);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Relaxed Fit Henley Shirt', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', 62, 46, 77167);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Whole Wheat Pita Bread', 'Morbi vel lectus in quam fringilla rhoncus.', 227, 14, 32784);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Reflective Safety Vest', 'Morbi porttitor lorem id ligula.', 44, 30, 89119);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pocket Blanket', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 430, 46, 33158);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Personal Safety Alarm', 'Vestibulum sed magna at nunc commodo placerat.', 458, 67, 55816);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pomegranate Juice', 'In quis justo.', 101, 39, 8598);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sliced Bread', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 305, 10, 89767);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Kitchen Scale', 'In hac habitasse platea dictumst.', 304, 23, 60816);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Plant-Based Protein Bars', 'Suspendisse potenti.', 55, 34, 58553);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Watercolor Paint Set', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 366, 38, 54726);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Joy Protein Bars', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.', 14, 26, 67629);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Luxury Bath Robe', 'Aenean sit amet justo.', 135, 18, 42423);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Kitchen Scale', 'Aenean sit amet justo. Morbi ut odio.', 177, 12, 33615);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Frozen Broccoli', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 267, 46, 83422);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Crispy Onion Rings', 'Donec semper sapien a libero. Nam dui.', 254, 57, 19758);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ethically-Sourced Coffee Beans', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 33, 32, 45346);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Honey', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 462, 47, 86956);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Eco-Friendly Disposable Plates', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 210, 49, 40680);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Curry Chicken', 'Mauris ullamcorper purus sit amet nulla.', 79, 57, 4495);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coffee Grinder', 'Integer non velit.', 346, 18, 14884);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Stainless Steel Water Pitcher', 'Aliquam quis turpis eget elit sodales scelerisque.', 183, 35, 9477);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Teriyaki Chicken Wings', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 286, 56, 85720);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dark Chocolate Raisins', 'Morbi a ipsum. Integer a nibh.', 284, 17, 40352);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Camera Tripod', 'Nulla facilisi.', 379, 8, 85599);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Berry Smoothie Mix', 'Fusce posuere felis sed lacus.', 66, 5, 88477);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Garlic Naan Bread', 'Etiam vel augue.', 351, 43, 84766);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Mini Indoor Hydroponic Garden', 'Donec posuere metus vitae ipsum.', 178, 64, 87026);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sliced Cucumbers', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.', 287, 25, 18683);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Flour Biscuits', 'Curabitur convallis.', 395, 33, 54449);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vintage Graphic Tee', 'Pellentesque ultrices mattis odio.', 108, 73, 6678);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Coconut Cashew Yogurt', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 94, 14, 47939);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Joy Snack Bars', 'Donec dapibus. Duis at velit eu est congue elementum.', 58, 7, 37403);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Laptop Stand', 'Sed ante.', 333, 50, 30223);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Sesame Ginger Dressing', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 234, 50, 84242);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegetable Spring Rolls', 'Morbi a ipsum. Integer a nibh.', 264, 34, 39455);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Opener for Jars and Bottles', 'Pellentesque at nulla. Suspendisse potenti.', 464, 33, 55829);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Campfire', 'Phasellus in felis. Donec semper sapien a libero.', 59, 11, 28835);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ginger Turmeric Tea', 'Praesent blandit lacinia erat.', 266, 46, 60407);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Zesty Cilantro Lime Dressing', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 472, 48, 78035);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Pumpkin Soup', 'Vestibulum ac est lacinia nisi venenatis tristique.', 412, 40, 62109);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Customizable Name Puzzle', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 249, 7, 60552);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cocktail Shaker and Mixing Glass Set', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 282, 35, 68226);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Gaming Mousepad', 'Fusce consequat. Nulla nisl.', 405, 43, 33131);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Adjustable Skipping Rope', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 210, 49, 70436);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Thai Peanut Dressing', 'In quis justo.', 142, 46, 34175);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chickpea Salad Deluxe', 'Ut at dolor quis odio consequat varius. Integer ac leo.', 213, 19, 60612);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Stir Fry Pan', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 409, 74, 57272);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cranberry Orange Oatmeal', 'Quisque id justo sit amet sapien dignissim vestibulum.', 187, 5, 88982);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Comfort Flats', 'Nunc rhoncus dui vel sem. Sed sagittis.', 64, 74, 28342);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Green Apples', 'Pellentesque at nulla. Suspendisse potenti.', 437, 65, 28521);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Tomato Paste', 'Vivamus vestibulum sagittis sapien.', 62, 66, 59452);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ginger Turmeric Tea', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 254, 75, 62947);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Corn Tortillas', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.', 437, 5, 8594);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Savory Snack Mix', 'In blandit ultrices enim.', 460, 23, 43970);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Vegan Caesar Dressing', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 353, 11, 17575);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Elegant Lace Dress', 'Nulla tempus.', 258, 43, 34204);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Organic Fruit Salad', 'Nulla suscipit ligula in lacus.', 477, 25, 67457);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Projector', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 78, 75, 13859);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chilli Lime Corn on the Cob', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 379, 13, 43168);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cotton Basic Tank', 'Nunc purus.', 213, 35, 63945);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fitness Tracker', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 263, 48, 23925);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Cabbage', 'Integer ac leo. Pellentesque ultrices mattis odio.', 225, 52, 76639);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Athletic Jogging Jacket', 'Suspendisse potenti.', 66, 23, 43741);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pineapple Chunks (canned)', 'Aenean auctor gravida sem.', 315, 8, 38543);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Jump Starter', 'Duis mattis egestas metus.', 126, 42, 73685);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pork Tenderloin', 'Etiam faucibus cursus urna.', 448, 45, 20063);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Stuffed Grape Leaves', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 416, 14, 35746);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Electric Meat Grinder', 'Aenean lectus. Pellentesque eget nunc.', 406, 12, 5016);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('BBQ Lentil Chips', 'In quis justo. Maecenas rhoncus aliquam lacus.', 159, 73, 45679);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Kids'' Gardening Kit', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 323, 60, 12929);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Bamboo Charcoal Air Purifier Bags', 'Nunc rhoncus dui vel sem.', 217, 19, 61261);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Caramel Apple Chips', 'Integer tincidunt ante vel ipsum.', 343, 17, 14984);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pet Grooming Gloves', 'Mauris ullamcorper purus sit amet nulla.', 309, 14, 2465);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Portable Refrigerator Freezer', 'Morbi quis tortor id nulla ultrices aliquet.', 334, 66, 51267);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Magnetic Whiteboard', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.', 126, 52, 43156);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Ginger Turmeric Latte Mix', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 30, 68, 87566);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pretzel Bites', 'Donec semper sapien a libero.', 308, 75, 77884);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Belted Trench Coat', 'Duis mattis egestas metus.', 84, 5, 77424);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Elegant Lace Dress', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 459, 10, 46886);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Inspirational Wall Art', 'Nullam molestie nibh in lectus.', 109, 44, 34416);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Noise Reduction Headphones', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 149, 10, 84138);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wireless Charging Station', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 190, 30, 46581);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Chili Beans (canned)', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 339, 67, 64335);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Luggage Scale', 'Proin at turpis a pede posuere nonummy. Integer non velit.', 241, 47, 78833);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Bamboo Memory Foam Pillow', 'Aliquam quis turpis eget elit sodales scelerisque.', 455, 19, 10627);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Pumpkin Waffles', 'Maecenas ut massa quis augue luctus tincidunt.', 371, 49, 49513);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fitness Tracker', 'Fusce consequat. Nulla nisl.', 115, 38, 67862);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Travel Jewelry Organizer', 'Nulla facilisi.', 195, 22, 11710);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Spicy Beef Taco Mix', 'Aenean lectus.', 136, 12, 13598);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Fruit and Nut Energy Bites', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 281, 69, 54597);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Smart Water Bottle with Hydration Reminder', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 414, 75, 59355);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Handmade Leather Journal', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 113, 42, 70964);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Digital Food Scale', 'Suspendisse potenti. In eleifend quam a odio.', 75, 6, 10730);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Leek and Potato Soup', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 206, 25, 73764);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Almond Quinoa Salad', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 220, 71, 65273);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Dog Collar', 'Nam tristique tortor eu pede.', 314, 60, 86258);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wall Calendar', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 495, 23, 51580);
insert into Part (PartName, Description, CurrentStock, ReorderThreshold, UnitPrice) values ('Wild Rice Pilaf', 'Integer tincidunt ante vel ipsum.', 309, 42, 89205);
